package com.iflytek.cloud.resource;

import com.alibaba.sdk.android.mns.common.MNSConstants;

public class b {
    public static String[] a = new String[]{"Powered by <a href=\"http://dev.voicecloud.cn/msc/help.html\">iFLYTEK</a> ", "http://dev.voicecloud.cn/msc/help.html", "I know", "Details", "Cancel", "Done", "Settings", "More", "Restart", "Retry", "Replay", "Request result", "1.Please keep moderate speech\n2.Away from mic about 10 centimeters\n3.Please use it in a relative quiet environment\n4.Severel words can be once", "1.Please keep moderate speech\n2.Away from mic about 10 centimeters\n3.Please use it in a relative quiet environment\n"};
    public static String[] b = new String[]{"Help", "Connecting server...", "Speak now", "Getting result...", "Getting audio...", MNSConstants.ERROR_TAG, "iFLYTEK TTS", "Uploading data"};
    public static String[] c = new String[]{"", "Network failure", "Access result timeout", "Invalid network connection", "Permission denied", "Invalid result", "Connect to server failed", "Invalid parameter", "Unexpected error", "Recording failed", "No match", "No speech detected", "Coding error", "Invalid text", "Open file failed", "Audioplayer error", "Out of memory", "Text overflow", "Login check failed", "Network is busy", "Invalid data", "Invalid grammar", "Local resource failed", "invalid user", "invalid password", "Permission denied VoiceApp", "Browser not installed", "engine busy,please wait", "engine init fail", "engine not installed", "local engine error", "script error", "invalid authorization", "No picture detected", "Picture no content", "Silent or low volume", "Noisy or short audio", "Not paper data", "Wrong paper content", "Wrong audio format", "Other data exception", "Wrong paper format", "Exist unlisted word", "Face not detected", "Face inclined to left", "Face inclined to right", "Face clockwise rotated", "Face anti-clockwise rotated", "Wrong image size", "Abnormal illumination", "Face occultation", "Invalid model", "Illegal input type", "Incomplete input", "Too much input data", "Kernel exception", "Rgn exceeded 9", "Truncated sonic wave", "Too much noise", "Low volume", "Zero audio", "Short audio", "Mismatching audio", "No enough audio", "Model not found", "Model is creating", "Already existed", "Group not existed", "Group is empty", "User not in group", "Overflow"};
    public static String[] d = new String[]{"Error code", "Unexpected error"};
}
