package org.apache.commons.httpclient;

import cn.v6.sixrooms.socket.common.SocketUtil;

public class Header extends NameValuePair {
    private boolean isAutogenerated;

    public Header() {
        this(null, null);
    }

    public Header(String str, String str2) {
        super(str, str2);
        this.isAutogenerated = false;
    }

    public Header(String str, String str2, boolean z) {
        super(str, str2);
        this.isAutogenerated = false;
        this.isAutogenerated = z;
    }

    public String toExternalForm() {
        return new StringBuffer().append(getName() == null ? "" : getName()).append(": ").append(getValue() == null ? "" : getValue()).append(SocketUtil.CRLF).toString();
    }

    public String toString() {
        return toExternalForm();
    }

    public HeaderElement[] getValues() throws HttpException {
        return HeaderElement.parse(getValue());
    }

    public HeaderElement[] getElements() {
        return HeaderElement.parseElements(getValue());
    }

    public boolean isAutogenerated() {
        return this.isAutogenerated;
    }
}
